# Generated by Django 5.2.9 on 2025-12-22 19:36

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='¿Eliminado?')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Nombre Paciente')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
